### ISSUE TITLE
Generate the intermediate scripts on the fly

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-tck#22]
When running in Java, call out to the TCK classes to generate the script from the Scala DSL.  This could be a command line for the C++ to call.  This would avoid checking in intermediate text files.

**Comment by xytosis** [comment]
This might be more appropriate to file in the -java repo since it would require a modification of the driver to do so. Since there is already a script that can generate the intermediate scripts, the Java driver can do it that way as well to avoid having to import code.
