### ISSUE TITLE
Java TCK client playing scripts out of order?

### ISSUE THREAD

**Issue by jakewins** [ReactiveSocket/reactivesocket-tck#24]
I'm trying to get `requestChannelSingleVsMulti` to pass for my Go server implementation. The script, on the server side, reads:

    channel%%c%%d%%{
    respond%%a-|
    request%%3%%8050983b-9135-47f6-8ad2-459bff8c3fb2
    await%%terminal%%8050983b-9135-47f6-8ad2-459bff8c3fb2
    assert%%received_n%%8050983b-9135-47f6-8ad2-459bff8c3fb2%%4
    assert%%no_error%%8050983b-9135-47f6-8ad2-459bff8c3fb2
    assert%%completed%%8050983b-9135-47f6-8ad2-459bff8c3fb2
    }

I'm interpreting this as:

- First, respond `a` and call `OnComplete`
- Then, request 3
- Then await terminal event and make assertions

However, when I do this, the Java Client sends EOF as soon as it sees the `Completed` message:

    [TCK] Server started, listening on [:4567]
    [Client C1] RequestChannel{streamId=2, initialRequestN=1, metadata=[64], data=[63]}
    [Server C1] Response{streamId=2, metadata=[61], data=[61]}
    [Server C1] Response[Complete]{streamId=2, metadata=[], data=[]}
    [Server C1] RequestN{streamId=2, N=3}
    [Client C1] EOF

Which then fails the test, since the stream is closed with EOF instead of OnComplete and we never see the three client messages. When I play the same script using the Java TCK Server, it seems to play it out of order, sending `request 3` before it sends `OnComplete`:

    INFO: ON NEXT GOT : c d
    INFO: PASSED: got 1 out of 1 values expected
    requested 1
    INFO: responding
    INFO: requesting 3
    adding a-|

This seems wrong to me. If the server is supposed to first `request 3` and then `respond a-|`, shouldn't the script say so? Alternatively, if the lines in the script are supposed to be re-ordered, what are the re-ordering rules?

As an aside - most of the TCK tests are now green for my little Go server implementation :) https://github.com/jakewins/reactivesocket-go

**Comment by xytosis** [comment]
Hey @jakewins that's definitely an excellent question and it was pretty hard to get the logic down while I was writing this having only the Java version available. The I/O is all asynchronous, so the ordering of the request and respond shouldn't matter (I think I had respond then request just to "test" that the async worked).

If you dig into the code for the Java Server Driver, you'll see that when the TCK script line for 'respond' is called, it doesn't actually immediately respond, it just stages data to be sent, and another thread takes care of actually sending this data. In your case, it sounds like there might be some sort of race condition going on. I haven't been working on the project for a while, but in the case for channel, is it required that the client closes upon an onComplete? I understand that onComplete should signify that no more data is expected, but in the case of channel, perhaps the connection needs to stay open for additional requests from the other side?

On your aside, nice job! It very impressive that you've done so much, especially on your own!

**Comment by jakewins** [comment]
Ah, I see now, added a second thread per channel worker to play the marbles and that gives it the same behavior as the java server, nice.

https://github.com/jakewins/reactivesocket-go/blob/master/cmd/tck/main.go#L179

I do think that still retains a race condition - if solar flares causes the parser thread to yield the CPU right after it creates the marble thread, the marble stuff will get played before `request`, and the original scenario here will happen.. but that seems extremely unlikely, and the outcome would be a failed TCK test run, it wouldn't cause false positives.

That gets me through the whole TCK as far as the Java client is concerned; my server side still segfaults at the end lol, so I've got a bit more work there.

**Comment by xytosis** [comment]
Nice job, that's impressive! I understand the Java impl was also still under construction during the writing of the TCK so if things fail that don't make sense, specifically with reusing the same reactive socket object, that could be a cause.
